services:
  habittrove:
    image: thearyadev/habittrove:latest
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
      - "./backups:/app/backups"
    environment:
      AUTH_SECRET: your-secret-key-here
